// Invoice Service - Automated invoice generation and billing
import { withTransaction } from '../utils/dbTransaction.js';
import { NotFoundError } from '../errors/index.js';
import { logEvent } from '../utils/logger.js';
import financeRepo from '../repositories/FinanceRepository.js';

function runSerial(items, worker) {
  return items.reduce(
    (chain, item) => chain.then(() => worker(item)),
    Promise.resolve()
  );
}

/**
 * Build shipment-fee line items and accumulate base amount.
 */
function buildShipmentLineItems(shipments) {
  let baseAmount = 0;
  const shipmentLineItems = [];

  shipments.forEach((shipment) => {
    const shippingCost = parseFloat(shipment.shipping_cost) || 0;
    baseAmount += shippingCost;

    shipmentLineItems.push({
      shipmentId: shipment.id,
      description: `Shipment ${shipment.tracking_number} - Order ${shipment.order_number}`,
      itemType: 'shipping_fee',
      quantity: 1,
      unitPrice: shippingCost,
      amount: shippingCost,
    });
  });

  return { baseAmount, shipmentLineItems };
}

/**
 * Build penalty line items and accumulate total penalties.
 */
function buildPenaltyLineItems(penalties) {
  let totalPenalties = 0;
  const penaltyLineItems = [];

  penalties.forEach((penalty) => {
    const penaltyAmount = parseFloat(penalty.penalty_amount) || 0;
    totalPenalties += penaltyAmount;

    penaltyLineItems.push({
      shipmentId: penalty.shipment_id,
      description: `SLA Penalty - ${penalty.tracking_number} (${penalty.delay_hours}h delay)`,
      itemType: 'penalty',
      quantity: 1,
      unitPrice: -penaltyAmount,
      amount: -penaltyAmount,
    });
  });

  return { totalPenalties, penaltyLineItems };
}

/**
 * Build fuel surcharge line item based on base freight amount.
 */
function buildFuelLineItem(baseAmount) {
  const fuelSurcharge = baseAmount * 0.05;
  return {
    fuelSurcharge,
    fuelLineItem: {
      shipmentId: null,
      description: 'Fuel Surcharge (5%)',
      itemType: 'fuel_surcharge',
      quantity: 1,
      unitPrice: fuelSurcharge,
      amount: fuelSurcharge,
    },
  };
}

/**
 * Persist invoice line items serially for deterministic writes.
 */
async function persistInvoiceLineItems(invoiceId, lineItems, tx) {
  await runSerial(lineItems, async (lineItem) => {
    await financeRepo.createInvoiceLineItem({
      invoiceId,
      shipmentId: lineItem.shipmentId,
      description: lineItem.description,
      itemType: lineItem.itemType,
      quantity: lineItem.quantity,
      unitPrice: lineItem.unitPrice,
      amount: lineItem.amount,
    }, tx);
  });
}

// ─── Invoice State Machine ──────────────────────────────────────────────────────────────────
// Single source of truth for valid invoice status transitions (TASK-R9-020).
// Imported by financeController; do not redefine inline.
export const INVOICE_VALID_TRANSITIONS = {
  pending:   ['approved', 'disputed', 'cancelled'],
  approved:  ['paid', 'disputed'],
  disputed:  ['approved', 'cancelled'],
  paid:      [],  // terminal
  cancelled: [],  // terminal
};

class InvoiceService {
  /**
   * Generate invoice for carrier for a billing period
   * Includes shipments, penalties, adjustments
   */
  async generateInvoiceForCarrier(carrierId, billingPeriodStart, billingPeriodEnd, jobId = null) {
    return withTransaction(async (tx) => {
      const carrier = await financeRepo.findCarrierById(carrierId, tx);
      if (!carrier) {
        throw new NotFoundError('Carrier not found');
      }

      const shipments = await financeRepo.findShipmentsForCarrierPeriod(carrierId, billingPeriodStart, billingPeriodEnd, tx);
      if (shipments.length === 0) {
        logEvent('InvoiceGenerationSkipped', {
          carrierId,
          carrier: carrier.name,
          reason: 'No completed shipments in period'
        });
        return null;
      }

      const { baseAmount, shipmentLineItems } = buildShipmentLineItems(shipments);
      const penalties = await financeRepo.findPenaltiesForCarrierPeriod(carrierId, billingPeriodStart, billingPeriodEnd, tx);
      const { totalPenalties, penaltyLineItems } = buildPenaltyLineItems(penalties);
      const { fuelSurcharge, fuelLineItem } = buildFuelLineItem(baseAmount);

      const finalAmount = baseAmount + fuelSurcharge - totalPenalties;
      const invoiceNumber = `INV-${carrier.code}-${Date.now()}`;
      const paymentDueDate = new Date(billingPeriodEnd);
      paymentDueDate.setDate(paymentDueDate.getDate() + 30);

      const invoice = await financeRepo.createAutoGeneratedInvoice({
        invoiceNumber,
        carrierId,
        billingPeriodStart,
        billingPeriodEnd,
        totalShipments: shipments.length,
        baseAmount,
        penalties: totalPenalties,
        adjustments: fuelSurcharge,
        finalAmount,
        jobId,
        paymentDueDate
      }, tx);

      const allLineItems = [...shipmentLineItems, ...penaltyLineItems, fuelLineItem];
      await persistInvoiceLineItems(invoice.id, allLineItems, tx);

      logEvent('InvoiceGenerated', {
        invoiceId: invoice.id,
        invoiceNumber,
        carrierId,
        carrierName: carrier.name,
        billingPeriod: `${billingPeriodStart} to ${billingPeriodEnd}`,
        totalShipments: shipments.length,
        finalAmount,
        autoGenerated: true
      });

      return invoice;
    });
  }

  /**
   * Generate invoices for all active carriers
   * Typically run monthly as a background job
   */
  async generateMonthlyInvoices(month, year, organizationId = undefined) {
    // Calculate billing period
    const periodStart = new Date(year, month - 1, 1);
    const periodEnd = new Date(year, month, 1);

    const carriers = await financeRepo.findCarriersForInvoicePeriod(
      periodStart.toISOString(),
      periodEnd.toISOString(),
      organizationId
    );

    const invoices = [];
    const errors = [];

    const outcomes = await Promise.allSettled(
      carriers.map((carrier) =>
        this.generateInvoiceForCarrier(
          carrier.id,
          periodStart.toISOString(),
          periodEnd.toISOString()
        ).then((invoice) => ({ carrierId: carrier.id, invoice }))
      )
    );

    outcomes.forEach((outcome, idx) => {
      const carrierId = carriers[idx]?.id;
      if (outcome.status === 'fulfilled') {
        if (outcome.value.invoice) invoices.push(outcome.value.invoice);
        return;
      }

      errors.push({
        carrierId,
        error: outcome.reason?.message || String(outcome.reason),
      });
    });

    logEvent('MonthlyInvoicesGenerated', {
      month,
      year,
      totalInvoices: invoices.length,
      errors: errors.length
    });

    return {
      invoices,
      errors,
      summary: {
        generated: invoices.length,
        failed: errors.length,
        totalAmount: invoices.reduce((sum, inv) => sum + parseFloat(inv.final_amount), 0)
      }
    };
  }

  /**
   * Get invoice with line items
   */
  async getInvoiceWithLineItems(invoiceId) {
    const invoice = await financeRepo.findInvoiceWithCarrier(invoiceId);

    if (!invoice) {
      throw new NotFoundError('Invoice not found');
    }

    // Get line items
    invoice.lineItems = await financeRepo.findInvoiceLineItems(invoiceId);

    return invoice;
  }

  /**
   * Approve invoice
   */
  async approveInvoice(invoiceId, approvedBy, organizationId = undefined) {
    const result = await financeRepo.approveInvoice(invoiceId, approvedBy, organizationId);

    if (!result) {
      throw new NotFoundError('Invoice not found or already processed');
    }

    logEvent('InvoiceApproved', {
      invoiceId,
      invoiceNumber: result.invoice_number,
      approvedBy
    });

    return result;
  }

  /**
   * Mark invoice as paid
   */
  async markInvoicePaid(invoiceId, paymentMethod, paymentDate, organizationId = undefined) {
    const result = await financeRepo.markInvoicePaid(invoiceId, paymentMethod, paymentDate, organizationId);

    if (!result) {
      throw new NotFoundError('Invoice not found or not approved');
    }

    logEvent('InvoicePaid', {
      invoiceId,
      invoiceNumber: result.invoice_number,
      paymentMethod,
      amount: result.final_amount
    });

    return result;
  }

  /**
   * Dispute invoice
   */
  async disputeInvoice(invoiceId, reason, disputedBy, organizationId = undefined) {
    const result = await financeRepo.disputeInvoice(invoiceId, organizationId);

    if (!result) {
      throw new NotFoundError('Invoice not found');
    }

    logEvent('InvoiceDisputed', {
      invoiceId,
      invoiceNumber: result.invoice_number,
      reason,
      disputedBy
    });

    return result;
  }

  /**
   * Get invoicing summary for a period
   */
  async getInvoicingSummary(startDate, endDate, organizationId = undefined) {
    return financeRepo.getInvoicingSummary(startDate, endDate, organizationId);
  }
}

export default new InvoiceService();
