// User & Auth Types
export type UserRole =
  | 'superadmin'
  | 'admin'
  | 'operations_manager'
  | 'warehouse_manager'
  | 'carrier_partner'
  | 'finance'
  | 'customer_support';

export interface User {
  id: string;
  email: string;
  name: string;
  avatar?: string;
  role: UserRole;
  organizationId: string | null; // null for superadmin
  impersonation?: {
    isImpersonating: boolean;
    byUserId: string;
    byEmail?: string;
    byRole?: string;
    startedAt?: string;
  } | null;
  createdAt: string;
  lastLogin: string;
}

export interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
}

// Order Types
export type OrderStatus =
  | 'created'
  | 'confirmed'
  | 'allocated'
  | 'pending_carrier_assignment'
  | 'processing'
  | 'ready_to_ship'
  | 'shipped'
  | 'in_transit'
  | 'out_for_delivery'
  | 'delivered'
  | 'returned'
  | 'cancelled'
  | 'on_hold';

export type OrderPriority = 'express' | 'standard' | 'bulk' | 'same_day';

export interface OrderItem {
  id: string;
  productId: string;
  productName: string;
  sku: string;
  quantity: number;
  unitPrice: number;
  weight: number;
  discount?: number;
  tax?: number;
  totalPrice?: number;
  isFragile?: boolean;
  isHazardous?: boolean;
  isPerishable?: boolean;
  requiresColdStorage?: boolean;
  itemType?: string;
  packageType?: string;
  warehouseId?: string;
}

export interface Order {
  id: string;
  orderNumber: string;
  customerId: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  status: OrderStatus;
  priority: OrderPriority;
  items: OrderItem[];
  shippingAddress: Address;
  billingAddress: Address;
  totalAmount: number;
  currency: string;
  shipmentId?: string;
  createdAt: string;
  updatedAt: string;
  estimatedDelivery?: string;
  actualDelivery?: string;
  notes?: string;
}

// Address Type
export interface Address {
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
}

// Shipment Types
export type ShipmentStatus =
  | 'pending'
  | 'picked_up'
  | 'in_transit'
  | 'at_hub'
  | 'out_for_delivery'
  | 'delivered'
  | 'failed_delivery'
  | 'returned';

export interface ShipmentEvent {
  id: string;
  shipmentId: string;
  status: ShipmentStatus;
  location: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
  timestamp: string;
  description: string;
  performedBy?: string;
}

export interface Shipment {
  id: string;
  trackingNumber: string;
  orderId: string;
  carrierId: string;
  carrierName: string;
  status: ShipmentStatus;
  origin: Address;
  destination: Address;
  currentLocation?: {
    lat: number;
    lng: number;
  };
  events: ShipmentEvent[];
  weight: number;
  dimensions?: {
    length: number;
    width: number;
    height: number;
  };
  estimatedDelivery: string;
  actualDelivery?: string;
  slaDeadline: string;
  cost: number;
  createdAt: string;
  updatedAt: string;
}

// Warehouse Types
export interface Warehouse {
  id: string;
  code: string;
  name: string;
  type: 'standard' | 'fulfillment' | 'distribution' | 'cold_storage' | 'hazmat' | 'bonded_customs' | 'returns_center';
  address: Address;
  capacity: number;
  currentUtilization: number;
  utilizationPercentage: number;
  inventoryCount: number;
  zones: number;
  location: {
    lat: number;
    lng: number;
  };
  status: 'active' | 'inactive';
  contactEmail: string;
  contactPhone: string;
  operatingHours: {
    open: string;
    close: string;
    timezone: string;
  };
  // SCM operational fields
  hasColdStorage: boolean;
  temperatureMinCelsius: number | null;
  temperatureMaxCelsius: number | null;
  customsBondedWarehouse: boolean;
  createdAt: string;
}

// Inventory Types
export interface InventoryItem {
  id: string;
  organizationId: string | null;
  productId: string | null;
  productName: string | null;
  sku: string | null;
  warehouseId: string;
  warehouseName: string | null;
  warehouseCode: string | null;
  quantity: number;
  availableQuantity: number;
  reservedQuantity: number;
  damagedQuantity: number;
  inTransitQuantity: number;
  productCategory: string | null;
  unitCost: number | null;
  reorderPoint: number | null;
  maxStockLevel: number | null;
  isLowStock: boolean;
  isOutOfStock: boolean;
  lastStockCheck: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface RestockOrderSummary {
  id: string;
  restockNumber: string | null;
  status: 'draft' | 'submitted' | 'confirmed' | 'in_transit' | 'received' | 'cancelled' | string;
  isAutoGenerated: boolean;
  totalItems: number;
  totalQuantity: number;
  lineItems: number;
  totalAmount: number;
  currency: string;
  supplierName: string;
  warehouseName: string;
  requestedAt: string;
  confirmedAt?: string | null;
  expectedArrival: string | null;
  receivedAt?: string | null;
  supplierPoNumber?: string | null;
  trackingNumber?: string | null;
}

// Product Catalog Types
export interface ProductDimensions {
  length?: number;
  width?: number;
  height?: number;
  unit?: string;
}

export type ProductPackageType = 'envelope' | 'box' | 'tube' | 'pallet' | 'crate' | 'bag' | 'custom';

export interface Product {
  id: string;
  organizationId: string | null;
  sku: string;
  name: string;
  description: string | null;
  category: string | null;
  brand: string | null;
  weight: number | null;
  dimensions: ProductDimensions | null;
  // Pricing
  sellingPrice: number | null;
  costPrice: number | null;
  mrp: number | null;
  currency: string;
  // Handling flags
  isFragile: boolean;
  requiresColdStorage: boolean;
  isHazmat: boolean;
  isPerishable: boolean;
  // Classification & shipping
  packageType: ProductPackageType | null;
  handlingInstructions: string | null;
  // Insurance & compliance
  requiresInsurance: boolean;
  // Customs
  countryOfOrigin: string | null;
  // Barcodes
  internalBarcode: string;
  // Warranty & shelf life
  warrantyPeriodDays: number;
  shelfLifeDays: number | null;
  // Supplier
  supplierId: string | null;
  // Flexible metadata
  tags: string[];
  attributes: Record<string, unknown> | null;
  // Computed
  volumetricWeight: number | null;
  // Status
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// Carrier Types
export interface Carrier {
  id: string;
  code: string;
  name: string;
  logo?: string;
  status: 'active' | 'inactive' | 'suspended';
  rating: number;
  onTimeDeliveryRate: number;
  exceptionRate: number;
  lossRate: number;
  averageDeliveryTime: number;
  activeShipments: number;
  totalShipments: number;
  services: string[];
  serviceAreas: string[];
  rateCard: RateCard[];
  contactEmail: string;
  contactPhone: string;
  website?: string;
  servicesOffered?: any;
  serviceType?: string;
  apiEndpoint?: string;
  webhookUrl?: string;
  createdAt: string;
}

export interface RateCard {
  id: string;
  carrierId: string;
  serviceType: string;
  originZone: string;
  destinationZone: string;
  weightMin: number;
  weightMax: number;
  baseRate: number;
  perKgRate: number;
  fuelSurcharge: number;
  effectiveFrom: string;
  effectiveTo: string;
}

// SLA Types
export type SLAStatus = 'on_track' | 'at_risk' | 'breached';

export interface SLAPolicy {
  id: string;
  name: string;
  serviceType: string;
  carrierId?: string | null;
  carrierName?: string | null;
  targetDeliveryHours: number;
  warningThresholdPercent: number;
  warningThresholdHours: number;
  penaltyAmount: number;
  maxPenaltyAmount?: number | null;
  penaltyType: 'fixed' | 'percentage';
  isActive: boolean;
  priority: number;
  createdAt: string;
}

export interface SLAViolation {
  id: string;
  shipmentId: string;
  orderId: string;
  policyId: string;
  policyName: string;
  expectedDelivery: string;
  actualDelivery?: string;
  delayHours: number;
  status: 'open' | 'acknowledged' | 'investigating' | 'resolved' | 'waived' | 'disputed';
  penaltyAmount: number;
  carrierId?: string;
  carrierName?: string;
  rootCause?: string;
  notes?: string;
  violatedAt?: string;
  createdAt: string;
  resolvedAt?: string;
}

export interface SLADashboardData {
  overallCompliance: number;
  totalShipments: number;
  onTimeDeliveries: number;
  violations: { pending: number; resolved: number; waived: number };
  topCarriers: unknown[];
}

// Return Types
export type ReturnStatus =
  | 'requested'
  | 'approved'
  | 'rejected'
  | 'pickup_scheduled'
  | 'picked_up'
  | 'in_transit'
  | 'received'
  | 'inspecting'
  | 'inspection_passed'
  | 'inspection_failed'
  | 'refunded'
;

export type ReturnReason =
  | 'damaged'
  | 'wrong_item'
  | 'not_as_described'
  | 'changed_mind'
  | 'quality_issue'
  | 'late_delivery'
  | 'other';

export interface Return {
  id: string;
  rmaNumber: string;
  orderId: string;
  orderNumber: string;
  customerId?: string;
  customerName: string;
  customerEmail?: string;
  status: ReturnStatus;
  reason: ReturnReason;
  reasonDetail?: string;
  notes?: string;
  items: ReturnItem[];
  pickupAddress?: Address;
  warehouseId?: string;
  shipmentId?: string;
  trackingNumber?: string;
  refundAmount?: number;
  restockingFee?: number;
  refundStatus?: 'pending' | 'processed' | 'failed';
  qualityCheckResult?: 'pass' | 'fail' | 'partial';
  qualityCheckNotes?: string;
  requestedAt?: string;
  createdAt: string;
  updatedAt?: string;
  approvedAt?: string;
  receivedAt?: string;
  resolvedAt?: string;
}

export interface ReturnItem {
  id: string;
  productId: string;
  productName: string;
  name: string;
  sku: string;
  quantity: number;
  condition?: 'new' | 'good' | 'damaged' | 'defective';
}

// Exception Types
export type ExceptionType =
  | 'delay'
  | 'damage'
  | 'lost_shipment'
  | 'address_issue'
  | 'carrier_issue'
  | 'inventory_issue'
  | 'sla_breach'
  | 'delivery_failed'
  | 'customer_not_available'
  | 'other';

export type ExceptionSeverity = 'low' | 'medium' | 'high' | 'critical';

export type ExceptionStatus =
  | 'open'
  | 'acknowledged'
  | 'investigating'
  | 'in_progress'
  | 'pending_resolution'
  | 'resolved'
  | 'escalated'
  | 'closed';

export interface Exception {
  id: string;
  ticketNumber: string;
  shipmentId: string;
  trackingNumber?: string;
  orderId: string;
  orderNumber?: string;
  type: ExceptionType;
  severity: ExceptionSeverity;
  status: ExceptionStatus;
  title: string;
  description: string;
  rootCause?: string;
  resolution?: string;
  resolutionType?: 'reship' | 'refund' | 'credit' | 'escalate' | 'no_action';
  assignedTo?: string;
  assignedToName?: string;
  slaImpact: boolean;
  estimatedResolutionTime?: string;
  createdAt: string;
  updatedAt: string;
  resolvedAt?: string;
}

// Analytics Types
export interface DashboardMetrics {
  totalOrders: number;
  ordersChange: number;
  activeShipments: number;
  shipmentsChange: number;
  lowStockAlerts?: number;
  deliveryRate: number;
  deliveryRateChange: number;
  slaCompliance: number;
  slaComplianceChange: number;
  pendingReturns: number;
  returnsChange: number;
  activeExceptions: number;
  exceptionsChange: number;
  revenue: number;
  revenueChange: number;
  avgDeliveryTime: number;
  avgDeliveryTimeChange: number;
  // Order status breakdown
  ordersPending?: number;
  ordersProcessing?: number;
  ordersShipped?: number;
  ordersDelivered?: number;
  ordersCancelled?: number;
  ordersReturned?: number;
}

export interface ChartDataPoint {
  date: string;
  value: number;
  label?: string;
}

export interface CarrierPerformance {
  carrierId: string;
  carrierName: string;
  totalShipments: number;
  onTimeDeliveries: number;
  lateDeliveries: number;
  onTimeRate: number;
  avgDeliveryTime: number;
  rating: number;
  slaViolations: number;
}

export interface WarehouseUtilization {
  warehouseId: string;
  warehouseName: string;
  capacity: number;
  used: number;
  utilizationRate: number;
  inboundToday: number;
  outboundToday: number;
}

// Notification Types
export type NotificationType =
  | 'order'
  | 'shipment'
  | 'sla'
  | 'exception'
  | 'return'
  | 'system';

export interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  isRead: boolean;
  actionUrl?: string;
  createdAt: string;
}

// API Response Types
export interface ApiResponse<T> {
  data: T;
  message?: string;
  success: boolean;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface ApiError {
  message: string;
  code: string;
  details?: Record<string, string[]>;
}

// Filter & Sort Types
export interface FilterOptions {
  search?: string;
  status?: string[];
  dateFrom?: string;
  dateTo?: string;
  priority?: string[];
  carrierId?: string;
  warehouseId?: string;
}

export interface SortOptions {
  field: string;
  direction: 'asc' | 'desc';
}

export interface PaginationOptions {
  page: number;
  pageSize: number;
}

// Re-export API types
export * from './api';
